services:
  hydra:
    image: oryd/hydra:v2.2
    command: serve public --dev -c /etc/config/hydra/hydra.yml
    volumes:
      - .docker/hydra:/etc/config/hydra:ro
    environment:
      - DSN=postgres://hydra:secret@hydra-postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    env_file:
      - .env.production
      - .env
    restart: unless-stopped
    depends_on:
      - hydra-migrate
      - hydra-postgresd

  hydra-admin:
    image: oryd/hydra:v2.2
    command: serve admin -c /etc/config/hydra/hydra.yml
    ports:
      - 4445:4445
    volumes:
      - .docker/hydra:/etc/config/hydra:ro
    environment:
      - DSN=postgres://hydra:secret@hydra-postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    env_file:
      - .env.production
      - .env
    restart: unless-stopped
    depends_on:
      - hydra-migrate
      - hydra-postgresd

  hydra-migrate:
    image: oryd/hydra:v2.2
    depends_on:
      - hydra-postgresd
    environment:
      - DSN=postgres://hydra:secret@hydra-postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    env_file:
      - .env.production
      - .env
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - .docker/hydra:/etc/config/hydra:ro
    restart: on-failure

  hydra-postgresd:
    image: postgres:17
    restart: always
    volumes:
      - hdyra_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - hydra
    ports:
      - 4455:4455
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    restart: on-failure
    volumes:
      - .docker/oathkeeper:/etc/config/oathkeeper:ro

  hydra-login-consent:
    build:
      context: ./hydra-login-consent
    environment:
      - HYDRA_ADMIN_URL=http://hydra-admin:4445
      - PORT=8080
    restart: unless-stopped
    depends_on:
      - hydra-admin

volumes:
  hdyra_db_data:
