name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.22"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./hydra-login-consent

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        working-directory: ${{ env.working-directory }}
        run: go build -v ./...
